//! The desktop and Android app: `ezcount-core` (in `../core`) exposed as Tauri commands, plus
//! the background sync loop and the native bits (window icons, deep links, share sheet).

mod background;
#[cfg(target_os = "android")]
mod bars;
#[cfg(target_os = "android")]
mod notify;
#[cfg(target_os = "android")]
mod share;

mod commands;
#[cfg(windows)]
mod icons;

use ezcount_core::storage::Store;
use ezcount_core::AppState;
use std::path::PathBuf;
use tauri::Manager;

pub fn create_specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
        commands::groups::get_groups,
        commands::groups::get_group,
        commands::groups::create_group,
        commands::groups::import_group_csv,
        commands::groups::export_group_csv,
        commands::expenses::suggest_exchange_rate,
        commands::groups::leave_group,
        commands::groups::delete_group,
        commands::groups::refuse_group_deletion,
        commands::groups::set_group_archived,
        commands::groups::update_group,
        commands::groups::add_participant,
        commands::groups::rename_participant,
        commands::groups::remove_participant,
        commands::expenses::add_expense,
        commands::expenses::update_expense,
        commands::expenses::delete_expense,
        commands::expenses::restore_expense,
        commands::expenses::purge_expense,
        commands::expenses::stop_recurring_expense,
        commands::expenses::record_reimbursement,
        commands::groups::get_balances,
        commands::groups::get_settlements,
        commands::groups::get_storage_warnings,
        commands::groups::get_sync_info,
        commands::groups::sync_now,
        commands::groups::join_group,
        commands::account::get_account,
        commands::account::update_profile,
        commands::expenses::add_expense_comment,
        commands::expenses::delete_expense_comment,
        commands::account::sign_up,
        commands::account::log_in,
        commands::account::log_out,
        commands::account::delete_account,
        commands::account::set_identity,
        commands::account::add_self,
        commands::native::native_features,
        commands::native::share_text,
        commands::native::set_bars_color,
        commands::native::share_file,
        commands::native::save_download,
        commands::native::save_file,
        commands::account::password_strength,
        commands::account::send_feedback,
        commands::account::receive_link,
        commands::account::receive,
        commands::account::send_login,
        commands::account::send_group_invite,
        commands::account::recover_account,
        commands::account::change_password,
        commands::account::replace_recovery_key,
        commands::account::create_login_link,
        commands::account::log_in_with_link
    ])
}

/// Writes `src/bindings.ts`. Used by both the debug app startup and the `export_bindings`
/// binary (pre-commit hook), so the two always produce identical files.
pub fn export_bindings(
    builder: &tauri_specta::Builder<tauri::Wry>,
) -> Result<std::path::PathBuf, String> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/bindings.ts");
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header(
                    "// @ts-nocheck\n// Auto-generated by tauri-specta. Do not edit manually.\n",
                ),
            &path,
        )
        .map_err(|e| format!("Failed to export TypeScript bindings: {e:?}"))?;
    Ok(path)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = create_specta_builder();

    #[cfg(all(debug_assertions, not(mobile)))]
    export_bindings(&builder).expect("Failed to export typescript bindings");

    let mut app = tauri::Builder::default();
    // First, so a second launch (say, from an invite link) hands its link to this instance
    // and quits.
    #[cfg(desktop)]
    {
        app = app.plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.unminimize();
                let _ = window.set_focus();
            }
        }));
    }
    app = app
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_deep_link::init());
    #[cfg(mobile)]
    {
        app = app.plugin(tauri_plugin_barcode_scanner::init());
    }
    #[cfg(target_os = "android")]
    {
        app = app
            .plugin(share::init())
            .plugin(notify::init())
            .plugin(bars::init());
    }

    #[cfg(windows)]
    {
        // Moved to a screen with another scale: load the icons drawn for that size.
        app = app.on_window_event(|window, event| {
            if let tauri::WindowEvent::ScaleFactorChanged { .. } = event {
                if let Ok(hwnd) = window.hwnd() {
                    icons::set_crisp_window_icons(hwnd.0);
                }
            }
        });
    }

    app.setup(|app| {
        #[cfg(windows)]
        {
            if let Some(window) = app.get_webview_window("main") {
                if let Ok(hwnd) = window.hwnd() {
                    icons::set_crisp_window_icons(hwnd.0);
                }
            }
        }

        // Installers register the ezcount:// scheme; this covers portable copies. Not dev
        // builds: links would start a debug copy outside `tauri dev`, without its dev server,
        // and that copy would then hold the single instance. Pasting invites always works.
        #[cfg(all(any(windows, target_os = "linux"), not(debug_assertions)))]
        {
            use tauri_plugin_deep_link::DeepLinkExt;
            if let Err(e) = app.deep_link().register_all() {
                eprintln!("[deep-link] could not register ezcount://: {e}");
            }
        }

        let app_data = app
            .path()
            .app_data_dir()
            .unwrap_or_else(|_| PathBuf::from("./"));
        let (store, warnings) = Store::open(&app_data.join("ezcount.sqlite3"))?;
        for warning in &warnings {
            eprintln!("[storage] {warning}");
        }
        app.manage(AppState::new(store, warnings)?);
        #[cfg(target_os = "android")]
        notify::started(app.handle().clone());
        background::spawn_sync(app.handle().clone());
        Ok(())
    })
    .invoke_handler(builder.invoke_handler())
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
