mod engine;
pub mod models;
pub mod storage;

use chrono::{DateTime, Utc};
use std::path::PathBuf;
use tauri::{Manager, State};

use crate::models::{ExpenseSplit, Group, ParticipantBalance, SettlementTransfer};
use crate::storage::AppState;

#[tauri::command]
#[specta::specta]
fn get_groups(state: State<AppState>) -> Vec<Group> {
    state.get_groups()
}

#[tauri::command]
#[specta::specta]
fn get_group(state: State<AppState>, group_id: String) -> Result<Group, String> {
    state
        .get_group(&group_id)
        .ok_or_else(|| "Group not found".to_string())
}

#[tauri::command]
#[specta::specta]
fn create_group(
    state: State<AppState>,
    name: String,
    currency: String,
    participants: Vec<String>,
) -> Result<Group, String> {
    state.create_group(name, currency, participants)
}

#[tauri::command]
#[specta::specta]
fn delete_group(state: State<AppState>, group_id: String) -> Result<bool, String> {
    state.delete_group(&group_id)
}

#[tauri::command]
#[specta::specta]
fn add_participant(
    state: State<AppState>,
    group_id: String,
    name: String,
) -> Result<Group, String> {
    state.add_participant(&group_id, name)
}

#[tauri::command]
#[specta::specta]
fn add_expense(
    state: State<AppState>,
    group_id: String,
    title: String,
    amount_cents: i64,
    paid_by: String,
    splits: Vec<ExpenseSplit>,
    created_at: Option<DateTime<Utc>>,
) -> Result<Group, String> {
    state.add_expense(&group_id, title, amount_cents, paid_by, splits, created_at)
}

#[tauri::command]
#[specta::specta]
#[allow(clippy::too_many_arguments)]
fn update_expense(
    state: State<AppState>,
    group_id: String,
    expense_id: String,
    title: String,
    amount_cents: i64,
    paid_by: String,
    splits: Vec<ExpenseSplit>,
    created_at: Option<DateTime<Utc>>,
) -> Result<Group, String> {
    state.update_expense(
        &group_id,
        &expense_id,
        title,
        amount_cents,
        paid_by,
        splits,
        created_at,
    )
}

#[tauri::command]
#[specta::specta]
fn delete_expense(
    state: State<AppState>,
    group_id: String,
    expense_id: String,
) -> Result<Group, String> {
    state.delete_expense(&group_id, &expense_id)
}

#[tauri::command]
#[specta::specta]
fn get_balances(
    state: State<AppState>,
    group_id: String,
) -> Result<Vec<ParticipantBalance>, String> {
    match state.get_group(&group_id) {
        Some(group) => Ok(engine::calculate_balances(&group)),
        None => Err("Group not found".to_string()),
    }
}

#[tauri::command]
#[specta::specta]
fn get_settlements(
    state: State<AppState>,
    group_id: String,
) -> Result<Vec<SettlementTransfer>, String> {
    match state.get_group(&group_id) {
        Some(group) => Ok(engine::calculate_settlements(&group)),
        None => Err("Group not found".to_string()),
    }
}

#[tauri::command]
#[specta::specta]
fn record_reimbursement(
    state: State<AppState>,
    group_id: String,
    from_id: String,
    to_id: String,
    amount_cents: i64,
    notes: Option<String>,
) -> Result<Group, String> {
    state.record_reimbursement(&group_id, from_id, to_id, amount_cents, notes)
}

pub fn create_specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
        get_groups,
        get_group,
        create_group,
        delete_group,
        add_participant,
        add_expense,
        update_expense,
        delete_expense,
        record_reimbursement,
        get_balances,
        get_settlements
    ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = create_specta_builder();

    #[cfg(all(debug_assertions, not(mobile)))]
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header(
                    "// @ts-nocheck\n// Auto-generated by tauri-specta. Do not edit manually.\n",
                ),
            "../src/bindings.ts",
        )
        .expect("Failed to export typescript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .setup(|app| {
            let app_data = app
                .path()
                .app_data_dir()
                .unwrap_or_else(|_| PathBuf::from("./"));
            let file_path = app_data.join("ezcount_data.json");
            app.manage(AppState::new(file_path));
            Ok(())
        })
        .invoke_handler(builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
