// @ts-nocheck
// Auto-generated by tauri-specta. Do not edit manually.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getGroups() : Promise<Group[]> {
    return await TAURI_INVOKE("get_groups");
},
async getGroup(groupId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The first participant is the user.
 */
async createGroup(name: string, currency: string, participants: string[]) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_group", { name, currency, participants }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the group from the account, on all the user's devices. Other members keep it.
 */
async leaveGroup(groupId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("leave_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addParticipant(groupId: string, name: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_participant", { groupId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeParticipant(groupId: string, participantId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_participant", { groupId, participantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addExpense(groupId: string, title: string, amountCents: number, paidBy: string, splits: ExpenseSplit[], createdAt: string | null) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_expense", { groupId, title, amountCents, paidBy, splits, createdAt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateExpense(groupId: string, expenseId: string, title: string, amountCents: number, paidBy: string, splits: ExpenseSplit[], createdAt: string | null) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_expense", { groupId, expenseId, title, amountCents, paidBy, splits, createdAt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteExpense(groupId: string, expenseId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_expense", { groupId, expenseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordReimbursement(groupId: string, fromId: string, toId: string, amountCents: number, notes: string | null) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_reimbursement", { groupId, fromId, toId, amountCents, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBalances(groupId: string) : Promise<Result<ParticipantBalance[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_balances", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettlements(groupId: string) : Promise<Result<SettlementTransfer[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settlements", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStorageWarnings() : Promise<string[]> {
    return await TAURI_INVOKE("get_storage_warnings");
},
async getSyncInfo(groupId: string) : Promise<Result<SyncInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sync_info", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Syncs one group immediately. Failures are reported in the returned `last_error`.
 */
async syncNow(groupId: string) : Promise<Result<SyncInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_now", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async joinGroup(inviteCode: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("join_group", { inviteCode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAccount() : Promise<Result<AccountInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async signUp(serverUrl: string, username: string, password: string) : Promise<Result<SignedIn, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sign_up", { serverUrl, username, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logIn(serverUrl: string, username: string, password: string) : Promise<Result<AccountInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_in", { serverUrl, username, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the account and its groups from this device. Fails while changes are not uploaded,
 * unless `force` is set.
 */
async logOut(force: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_out", { force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records which participant the user is in a group.
 */
async setIdentity(groupId: string, participantId: string) : Promise<Result<AccountInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_identity", { groupId, participantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds the user to a group as a new participant.
 */
async addSelf(groupId: string, name: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_self", { groupId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What this platform can do natively, beyond the web view.
 */
async nativeFeatures() : Promise<NativeFeatures> {
    return await TAURI_INVOKE("native_features");
},
/**
 * Opens the system share sheet with `text`. Only where `native_features().share` is true.
 */
async shareText(text: string, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("share_text", { text, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * How hard a password is to guess. Signing up requires `acceptable`.
 */
async passwordStrength(password: string, username: string) : Promise<PasswordStrength> {
    return await TAURI_INVOKE("password_strength", { password, username });
},
/**
 * Sets a new password with the recovery key and logs in. Returns the replacement recovery
 * key: each one works once.
 */
async recoverAccount(serverUrl: string, username: string, recoveryKey: string, newPassword: string) : Promise<Result<SignedIn, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recover_account", { serverUrl, username, recoveryKey, newPassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePassword(currentPassword: string, newPassword: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_password", { currentPassword, newPassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A new recovery key, replacing the old one. Returned to show once.
 */
async replaceRecoveryKey(password: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_recovery_key", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AccountInfo = { username: string; server_url: string; identities: { [key in string]: string } }
export type Expense = { id: string; group_id: string; title: string; amount_cents: number; paid_by: string; splits: ExpenseSplit[]; created_at: string; updated_at: string; history?: ExpenseHistoryEntry[]; is_reimbursement?: boolean }
export type ExpenseHistoryEntry = { edited_at: string; previous_title: string; previous_amount_cents: number; previous_paid_by: string; previous_splits: ExpenseSplit[]; summary: string }
export type ExpenseSplit = { participant_id: string; shares: number }
export type Group = { id: string; name: string; currency: string; participants: Participant[]; expenses: Expense[]; created_at: string }
export type NativeFeatures = { share: boolean; scan: boolean }
export type Participant = { id: string; name: string; removed?: boolean }
export type ParticipantBalance = { participant_id: string; participant_name: string; paid_cents: number; owed_cents: number; net_cents: number; removed: boolean }
export type PasswordStrength = { score: number; acceptable: boolean; warning: string | null; suggestions: string[] }
export type SettlementTransfer = { from_id: string; from_name: string; to_id: string; to_name: string; amount_cents: number }
/**
 * After signing up or recovering an account.
 */
export type SignedIn = { account: AccountInfo; recovery_key: string | null }
export type SyncInfo = { group_id: string; enabled: boolean; server_url: string | null; invite_code: string | null; last_synced_at: string | null; last_error: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
