// @ts-nocheck
// Auto-generated by tauri-specta. Do not edit manually.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getGroups() : Promise<Group[]> {
    return await TAURI_INVOKE("get_groups");
},
async getGroup(groupId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The first participant is the user.
 */
async createGroup(name: string, currency: string, participants: string[]) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_group", { name, currency, participants }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a group from a CSV file's text, in the format `export_group_csv` writes. The user
 * then says who they are in it.
 */
async importGroupCsv(name: string, csv: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_group_csv", { name, csv }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The group as a CSV file's text: a line per expense, a column per person.
 */
async exportGroupCsv(groupId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_group_csv", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The exchange rate to suggest for an expense paid in `from` on `date` (`YYYY-MM-DD`) in a
 * group counting in `to`, from the account's relay. Null when it has none.
 */
async suggestExchangeRate(from: string, to: string, date: string | null) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_exchange_rate", { from, to, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the group from the account, on all the user's devices. Other members keep it.
 */
async leaveGroup(groupId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("leave_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Renames the group and sets its currency. Amounts are not converted.
 * Deletes the group for every member. While someone still owes something it takes
 * everyone's agreement: this gives the user's, and returns the group still waiting for the
 * others. Returns nothing once the group is deleted.
 */
async deleteGroup(groupId: string) : Promise<Result<Group | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refuses the deletion some members asked for, or takes the request back.
 */
async refuseGroupDeletion(groupId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refuse_group_deletion", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Puts a group away for the user (it stays theirs, listed apart), or back.
 */
async setGroupArchived(groupId: string, archived: boolean) : Promise<Result<AccountInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_group_archived", { groupId, archived }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateGroup(groupId: string, name: string, currency: string, description: string, image: string | null) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_group", { groupId, name, currency, description, image }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addParticipant(groupId: string, name: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_participant", { groupId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameParticipant(groupId: string, participantId: string, name: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_participant", { groupId, participantId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeParticipant(groupId: string, participantId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_participant", { groupId, participantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addExpense(groupId: string, expense: ExpenseInput) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_expense", { groupId, expense }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replaces an expense with what the form holds, recording what changed in its history.
 */
async updateExpense(groupId: string, expenseId: string, expense: ExpenseInput) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_expense", { groupId, expenseId, expense }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteExpense(groupId: string, expenseId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_expense", { groupId, expenseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Puts a deleted expense back.
 */
async restoreExpense(groupId: string, expenseId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_expense", { groupId, expenseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes a deleted expense from the trash, for good.
 */
async purgeExpense(groupId: string, expenseId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_expense", { groupId, expenseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops a repeated expense. The ones already added stay.
 */
async stopRecurringExpense(groupId: string, recurringId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recurring_expense", { groupId, recurringId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordReimbursement(groupId: string, fromId: string, toId: string, amountCents: number, notes: string | null) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_reimbursement", { groupId, fromId, toId, amountCents, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBalances(groupId: string) : Promise<Result<ParticipantBalance[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_balances", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettlements(groupId: string) : Promise<Result<SettlementTransfer[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settlements", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStorageWarnings() : Promise<string[]> {
    return await TAURI_INVOKE("get_storage_warnings");
},
async getSyncInfo(groupId: string) : Promise<Result<SyncInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sync_info", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Syncs one group immediately. Failures are reported in the returned `last_error`.
 */
async syncNow(groupId: string) : Promise<Result<SyncInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_now", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async joinGroup(inviteCode: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("join_group", { inviteCode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAccount() : Promise<Result<AccountInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sets the name, picture (a `data:` URL) and bank account (an IBAN, to be paid back on) the
 * user shows, in every group where they said who they are. An empty name keeps the names
 * the groups have.
 */
async updateProfile(name: string, avatar: string | null, iban: string | null) : Promise<Result<AccountInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_profile", { name, avatar, iban }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes a comment under an expense.
 */
async addExpenseComment(groupId: string, expenseId: string, text: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_expense_comment", { groupId, expenseId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes a comment from under an expense.
 */
async deleteExpenseComment(groupId: string, commentId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_expense_comment", { groupId, commentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async signUp(serverUrl: string, username: string, password: string) : Promise<Result<SignedIn, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sign_up", { serverUrl, username, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logIn(serverUrl: string, username: string, password: string) : Promise<Result<AccountInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_in", { serverUrl, username, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the account and its groups from this device. Fails while changes are not uploaded,
 * unless `force` is set.
 */
async logOut(force: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_out", { force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records which participant the user is in a group.
 */
async setIdentity(groupId: string, participantId: string) : Promise<Result<AccountInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_identity", { groupId, participantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds the user to a group as a new participant.
 */
async addSelf(groupId: string, name: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_self", { groupId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What this platform can do natively, beyond the web view.
 */
async nativeFeatures() : Promise<NativeFeatures> {
    return await TAURI_INVOKE("native_features");
},
/**
 * Opens the system share sheet with `text`. Only where `native_features().share` is true.
 */
async shareText(text: string, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("share_text", { text, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hands a file (a PDF, say) to the system share sheet, to send it or save it. Only where
 * `native_features().share` is true.
 */
async shareFile(fileName: string, mime: string, data: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("share_file", { fileName, mime, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves `text` as a file named `file_name` in the Downloads folder, next to any file of that
 * name already there, and returns where it is. Only where `native_features().save` is true.
 */
async saveDownload(fileName: string, text: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_download", { fileName, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The same for a file that isn't text, such as a PDF.
 */
async saveFile(fileName: string, data: number[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_file", { fileName, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * How hard a password is to guess. Signing up requires `acceptable`.
 */
async passwordStrength(password: string, username: string) : Promise<PasswordStrength> {
    return await TAURI_INVOKE("password_strength", { password, username });
},
/**
 * Sends an idea or a problem to whoever runs the account's relay. `contact` is how to
 * answer, when an answer is wanted; `app` says which app it comes from.
 */
async sendFeedback(message: string, contact: string | null, app: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_feedback", { message, contact, app }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The link a device shows as a QR code to get something from a phone that scans it:
 * `purpose` is "login" to be logged into the phone's account, "group" to join a group.
 */
async receiveLink(serverUrl: string, purpose: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("receive_link", { serverUrl, purpose }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Asks once whether a phone scanned the code this device shows (`receive_link`). Nothing
 * while none did; then the device is logged in, or has joined the group.
 */
async receive(link: string) : Promise<Result<Received | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("receive", { link }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Logs the device showing the scanned `link` into this account.
 */
async sendLogin(link: string, password: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_login", { link, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lets the device showing the scanned `link` join a group.
 */
async sendGroupInvite(groupId: string, link: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_group_invite", { groupId, link }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sets a new password with the recovery key and logs in. Returns the replacement recovery
 * key: each one works once.
 */
async recoverAccount(serverUrl: string, username: string, recoveryKey: string, newPassword: string) : Promise<Result<SignedIn, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recover_account", { serverUrl, username, recoveryKey, newPassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePassword(currentPassword: string, newPassword: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_password", { currentPassword, newPassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A new recovery key, replacing the old one. Returned to show once.
 */
async replaceRecoveryKey(password: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_recovery_key", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A link that logs another device into the account, once and for a short time. Shown as a
 * QR code.
 */
async createLoginLink(password: string) : Promise<Result<LoginLink, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_login_link", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Logs in with a link made by `create_login_link` on another device.
 */
async logInWithLink(link: string) : Promise<Result<AccountInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_in_with_link", { link }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AccountInfo = { username: string; server_url: string; display_name: string | null; avatar: string | null; iban?: string | null; archived: string[]; identities: { [key in string]: string } }
/**
 * An expense someone deleted, kept so it can be put back.
 */
export type DeletedExpense = { expense: Expense; deleted_at: string; deleted_by?: string | null }
export type Expense = { id: string; group_id: string; title: string; category?: string | null; amount_cents: number; original?: OriginalAmount | null; paid_by: string; payers?: ExpensePayer[]; splits: ExpenseSplit[]; created_at: string; updated_at: string; history?: ExpenseHistoryEntry[]; is_reimbursement?: boolean; income?: boolean; added_at?: string | null; added_by?: string | null; recurring?: string | null; items?: ExpenseItem[]; comments?: ExpenseComment[] }
/**
 * What a member wrote under an expense.
 */
export type ExpenseComment = { id: string; text: string; created_at: string; by?: string | null }
export type ExpenseHistoryEntry = { edited_at: string; previous_title: string; previous_amount_cents: number; previous_paid_by: string; previous_payers?: ExpensePayer[]; previous_splits: ExpenseSplit[]; previous_original?: OriginalAmount | null; previous_category?: string | null; summary: string; edited_by?: string | null }
/**
 * An expense as the form sends it, to add one or to replace one.
 */
export type ExpenseInput = { title: string; category?: string | null; amount_cents: number; paid_by: string; payers?: ExpensePayer[]; splits: ExpenseSplit[]; created_at?: string | null; original?: OriginalAmount | null; income?: boolean; repeat?: string | null; items?: ExpenseItem[] }
/**
 * One line of an expense detailed item by item: the people who share it, equally.
 */
export type ExpenseItem = { name: string; amount_cents: number; participants: string[] }
/**
 * What one of the several people who paid an expense put in.
 */
export type ExpensePayer = { participant_id: string; amount_cents: number }
export type ExpenseSplit = { participant_id: string; shares: number; fixed_cents?: number | null }
export type Group = { id: string; name: string; description?: string; image?: string | null; currency: string; participants: Participant[]; expenses: Expense[]; created_at: string; deleted?: boolean; deletion_votes?: string[]; trash?: DeletedExpense[]; recurring?: RecurringExpense[] }
/**
 * A link that logs another device into the account, shown as a QR code.
 */
export type LoginLink = { link: string; expires_in: number }
export type NativeFeatures = { share: boolean; scan: boolean; save?: boolean }
/**
 * What an expense paid in another currency than the group's cost there.
 */
export type OriginalAmount = { currency: string; amount_cents: number; rate: string }
export type Participant = { id: string; name: string; removed?: boolean; avatar?: string | null; iban?: string | null; added_at?: string | null; added_by?: string | null; removed_at?: string | null; removed_by?: string | null }
export type ParticipantBalance = { participant_id: string; participant_name: string; paid_cents: number; owed_cents: number; net_cents: number; removed: boolean }
export type PasswordStrength = { score: number; acceptable: boolean; warning: string | null; suggestions: string[] }
/**
 * What a device that showed a code got from the phone that scanned it.
 */
export type Received = { account: AccountInfo | null; group: Group | null }
/**
 * An expense that comes back every week, month or year: the app adds the next one when its
 * day comes.
 */
export type RecurringExpense = { id: string; title: string; category?: string | null; amount_cents: number; income?: boolean; paid_by: string; payers?: ExpensePayer[]; splits: ExpenseSplit[]; every: string; next: string; paused?: boolean; added_by?: string | null }
export type SettlementTransfer = { from_id: string; from_name: string; to_id: string; to_name: string; amount_cents: number }
/**
 * After signing up or recovering an account.
 */
export type SignedIn = { account: AccountInfo; recovery_key: string | null }
export type SyncInfo = { group_id: string; enabled: boolean; server_url: string | null; invite_code: string | null; last_synced_at: string | null; last_error: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
