// @ts-nocheck
// Auto-generated by tauri-specta. Do not edit manually.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getGroups() : Promise<Group[]> {
    return await TAURI_INVOKE("get_groups");
},
async getGroup(groupId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createGroup(name: string, currency: string, participants: string[]) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_group", { name, currency, participants }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the group from this device. Other members of a shared group keep it.
 */
async deleteGroup(groupId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addParticipant(groupId: string, name: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_participant", { groupId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeParticipant(groupId: string, participantId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_participant", { groupId, participantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addExpense(groupId: string, title: string, amountCents: number, paidBy: string, splits: ExpenseSplit[], createdAt: string | null) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_expense", { groupId, title, amountCents, paidBy, splits, createdAt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateExpense(groupId: string, expenseId: string, title: string, amountCents: number, paidBy: string, splits: ExpenseSplit[], createdAt: string | null) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_expense", { groupId, expenseId, title, amountCents, paidBy, splits, createdAt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteExpense(groupId: string, expenseId: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_expense", { groupId, expenseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordReimbursement(groupId: string, fromId: string, toId: string, amountCents: number, notes: string | null) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_reimbursement", { groupId, fromId, toId, amountCents, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBalances(groupId: string) : Promise<Result<ParticipantBalance[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_balances", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettlements(groupId: string) : Promise<Result<SettlementTransfer[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settlements", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStorageWarnings() : Promise<string[]> {
    return await TAURI_INVOKE("get_storage_warnings");
},
async getSyncInfo(groupId: string) : Promise<Result<SyncInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sync_info", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts sharing a group through a sync server and returns its invite code.
 */
async enableSync(groupId: string, serverUrl: string) : Promise<Result<SyncInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_sync", { groupId, serverUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Syncs one group immediately. Failures are reported in the returned `last_error`.
 */
async syncNow(groupId: string) : Promise<Result<SyncInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_now", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async joinGroup(inviteCode: string) : Promise<Result<Group, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("join_group", { inviteCode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Expense = { id: string; group_id: string; title: string; amount_cents: number; paid_by: string; splits: ExpenseSplit[]; created_at: string; updated_at: string; history?: ExpenseHistoryEntry[]; is_reimbursement?: boolean }
export type ExpenseHistoryEntry = { edited_at: string; previous_title: string; previous_amount_cents: number; previous_paid_by: string; previous_splits: ExpenseSplit[]; summary: string }
export type ExpenseSplit = { participant_id: string; shares: number }
export type Group = { id: string; name: string; currency: string; participants: Participant[]; expenses: Expense[]; created_at: string }
export type Participant = { id: string; name: string; removed?: boolean }
export type ParticipantBalance = { participant_id: string; participant_name: string; paid_cents: number; owed_cents: number; net_cents: number; removed: boolean }
export type SettlementTransfer = { from_id: string; from_name: string; to_id: string; to_name: string; amount_cents: number }
export type SyncInfo = { group_id: string; enabled: boolean; server_url: string | null; invite_code: string | null; last_synced_at: string | null; last_error: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
